---
# tasks file for db_postgresql
- name: Install dependencies
  ansible.builtin.include_tasks:
    file: "01_install_dependencies.yml"

- name: Install Postgres
  ansible.builtin.include_tasks:
    file: "02_install_app.yml"

- name: Create User
  ansible.builtin.include_tasks:
    file: "03_create_user.yml"

- name: Create DB
  ansible.builtin.include_tasks:
    file: "04_create_db.yml"

- name: Create HBA
  ansible.builtin.include_tasks:
    file: "05_create_hba.yml"